name: Rebuild Funding Data

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "data/**/*.csv"

jobs:
  rebuild:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Rebuild funding data
        run: uv run src/main.py

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/funding_data{.json,.csv}
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: rebuild funding data [skip ci]"
            git push origin main
          fi
