name: Rebuild Funding Data

on:
  push:
    branches:
      - main
    paths:
      - "data/**/*.csv"

jobs:
  rebuild:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Rebuild funding data
        run: uv run src/main.py

      - name: Commit changes
        id: commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/funding_data{.json,.csv}
          if git diff --staged --quiet; then
            echo "No changes to commit"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            git commit -m "chore: rebuild \`funding\` data"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Push changes and create PR
        if: steps.commit.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: rebuild `funding` data"
          branch: ci/rebuild-funding-data
          title: "chore: rebuild `funding` data"
          body: "Rebuild the `funding` data files"
          base: main
          delete-branch: true
          add-paths: |
            data/funding_data.json
            data/funding_data.csv
